import type { Metadata } from "next";
import { ClerkProvider } from "@clerk/nextjs";
import ServiceWorkerRegistration from "@/src/components/ServiceWorkerRegistration";
import TelemetrySyncProvider from "@/src/components/TelemetrySyncProvider";
import SyncManagerProvider from "@/src/components/SyncManagerProvider";
import QueryProvider from "@/src/components/providers/QueryProvider";
import "./globals.css";
import 'katex/dist/katex.min.css';

// Route segment config - prevents server action caching issues
export const dynamic = 'force-dynamic';

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <QueryProvider>
      <ClerkProvider
        // Clerk configuration
        // Note: The ERR_CONNECTION_REFUSED error for detectKeylessEnvDriftAction
        // is a known Clerk issue that occurs when the dev server restarts.
        // This is harmless and can be ignored - it's just Clerk checking for
        // environment configuration drift.
        signInFallbackRedirectUrl="/sign-in"
        signUpFallbackRedirectUrl="/sign-up"
      >
        <html lang="en">
          <body
            className="antialiased"
          >
            <ServiceWorkerRegistration />
            <TelemetrySyncProvider />
            <SyncManagerProvider />
            {children}
          </body>
        </html>
      </ClerkProvider>
    </QueryProvider>
  );
}
