"""Add items table

Revision ID: 4a8842409132
Revises: 5b31d68f78c7
Create Date: 2026-01-27 07:27:00.252418

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4a8842409132'
down_revision: Union[str, None] = '5b31d68f78c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('items',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('question_text', sa.String(), nullable=False),
    sa.Column('correct_answer', sa.Float(), nullable=False),
    sa.Column('options', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('template_id', sa.String(), nullable=True),
    sa.Column('context_type', sa.String(), nullable=True),
    sa.Column('variables', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_items_template_id'), 'items', ['template_id'], unique=False)
    op.create_index(op.f('ix_items_tenant_id'), 'items', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_items_tenant_id'), table_name='items')
    op.drop_index(op.f('ix_items_template_id'), table_name='items')
    op.drop_table('items')
    # ### end Alembic commands ###
