"""Add logical_id to items table

Revision ID: afe30ea3fd53
Revises: 4a8842409132
Create Date: 2026-01-27 07:52:10.867086

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'afe30ea3fd53'
down_revision: Union[str, None] = '4a8842409132'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('logical_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_items_logical_id'), 'items', ['logical_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_items_logical_id'), table_name='items')
    op.drop_column('items', 'logical_id')
    # ### end Alembic commands ###
