"""add_solution_text_and_skill_tag_to_items

Revision ID: b1c2d3e4f5a6
Revises: afe30ea3fd53
Create Date: 2026-01-27 12:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b1c2d3e4f5a6'
down_revision: Union[str, None] = 'afe30ea3fd53'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('solution_text', sa.String(), nullable=True))
    op.add_column('items', sa.Column('skill_tag', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('items', 'skill_tag')
    op.drop_column('items', 'solution_text')
    # ### end Alembic commands ###
